@baseUrl = http://localhost:8000/api
@token =47|N6JpSDU0rdyPFU2WXSbQxyuFN6KZKIMnR90rQ2eW32d2d321
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "user@gmail.com",
  "password": "123456"
}

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

###
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}
Accept: application/json

###
POST {{baseUrl}}/refresh
Authorization: Bearer {{token}}
Accept: application/json